from typing import List
import requests
import ollama
import time
import logging

class DeepSeekModel:

    @staticmethod
    def generate_syllabus(course_id, course_title, credits, department, prereqs, abstract):
        """
        Use DeepSeek-R1 model to generate a syllabus based on course title and abstract info.
        """
        my_model = "qwen2:0.5b"
        my_prompt = f"""
                        I would like you to generate a detailed course description and outline for {course_id}: a {course_title} course with {credits} from the {department} department. The prerequisites are {prereqs}. Please do not create any additional information beyond what is specified. Omit anything not provided or uncertain.

                        1. Course Description:

                        Begin with a brief, engaging introduction to the course, highlighting its importance and applications.
                        Focus on the real-world relevance of the course and what skills students will gain.
                        Keep the description brief and exciting.

                        2. Course Outline:

                        Provide a high-level outline of key topics to be covered in the course.
                        Ensure each topic is relevant and supports the goal of the course.
                        3. Week-by-Week Curriculum (15 Weeks):

                        Provide a sample curriculum for 15 weeks.
                        Each week should include a specific topic or focus.
                        Give topics for the whole week, not individual days.
                        Be sure to indicate the learning objectives for each week (what students should learn by the end of the week).
                        The plan should include suggested activities, readings, or assessments for each week.
                        Do not invent any fictional content beyond the outline; it should be realistic and based on typical course structures.
                        Make sure the tone remains exciting, and the course outline is applicable to real-world use cases of the subject.
                                               1. Course Description:

                        Begin with a brief, engaging introduction to the course, highlighting its importance and applications.
                        Focus on the real-world relevance of the course and what skills students will gain.
                        Keep the description brief and exciting.'''
        my_model = "qwen2:0.5b"
        my_prompt = f"""

                        I would like you to generate a detailed course description and outline for {course_id}: a {course_title} course with {credits} from the {department} department. The prerequisites are {prereqs}. Please do not create any additional information beyond what is specified. Omit anything not provided or uncertain.

 

                        2. Course Outline:

                        Provide a high-level outline of key topics to be covered in the course.
                        Ensure each topic is relevant and supports the goal of the course.
                        
                        
                    """.replace("\n", "")
        

        
        try:

            # Interact with the DeepSeek-R1 model via Ollama
            print("starting")
            time1 = time.time()
            response = ollama.generate(
                model=my_model, 
                prompt= my_prompt,
                options = {
                    "temperature": .2,
                    "top_p": .85
                }
            )
        
            # Extract only the response text
            if response and "response" in response:
                print("elapsed:", time.time() - time1)
                return response["response"]
            else:
                print("No response generated by the model.")
                return None
        except Exception as e:
            print(f"Error generating syllabus with Ollama: {e}")
            return None
